[workspace]
resolver = "2"
members = [
    "app",
    "cli",
    "lib",
    "rpc-api",
]

[workspace.package]
authors = [
    "Ash Manning <ash@layertwolabs.com>",
    "Nikita Chashchinskii <nikita.chashchinskii@gmail.com>"
]
edition = "2021"
version = "0.8.14"

[workspace.dependencies.bip300301]
git = "https://github.com/Ash-L2L/bip300301.git"
rev = "b74c5bbf6022701cbdfbd9a412327577e115ceda"

[workspace.dependencies.rustreexo]
git = "https://github.com/Ash-L2L/rustreexo.git"
rev = "6e220fd89b33b60d9ab9099926683c3010a62ede"

[profile.release]
# lto = "fat"
