[workspace]
resolver = "2"
members = [
    "app",
    "cli",
    "lib",
    "rpc-api",
]

[workspace.package]
authors = [
    "Ash Manning <ash@layertwolabs.com>",
    "Nikita Chashchinskii <nikita.chashchinskii@gmail.com>"
]
edition = "2021"
version = "0.8.3"

[workspace.dependencies.bip300301]
git = "https://github.com/Ash-L2L/bip300301.git"
rev = "64568dee7b89fe8c021226f10b17a18fe3386871"

[workspace.dependencies.rustreexo]
git = "https://github.com/Ash-L2L/rustreexo.git"
rev = "a3ac7d3ebe9749ebd0bb34c709e7616f83d573b3"

[profile.release]
# lto = "fat"
