[package]
name = "thunder_app"
version = "0.4.7"
edition = "2021"
authors = [ "Ash Manning <ash@layertwolabs.com>", "Nikita Chashchinskii <nikita.chashchinskii@gmail.com>" ]

[dev-dependencies]
base64 = "0.21.2"
futures = { version = "0.3.30", default-features = false, features = ["async-await"]}
jsonrpsee = { version = "0.20.0", features = ["http-client"] }
tempfile = "3.10.0"
test-log = { version = "0.2.14", features = ["trace"] }
tokio = { version = "1.29.1", features = ["process", "rt-multi-thread"] }

[dependencies]
anyhow = "1.0.72"
bincode = "1.3.3"
clap = { version = "4.3.19", features = ["derive"] }
ctrlc = "3.4.0"
dirs = "5.0.1"
eframe = "0.26.2"
human-size = "0.4.3"
jsonrpsee = { version = "0.20.0", features = ["client-core", "macros", "server"] }
parking_lot = "0.12.1"
serde = { version = "1.0.179", features = ["derive"] }
thiserror = "1.0.44"
thunder = { path = "../lib" }
tiny-bip39 = "1.0.0"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dependencies.bip300301]
git = "https://github.com/Ash-L2L/bip300301.git"
rev = "1bd864165a8cd1beaa1c7816b845d766ae563a3f"

[lib]
name = "thunder_app_rpc_api"
path = "rpc_api.rs"

[[bin]]
name = "thunder_app"
path = "main.rs"